### ISSUE TITLE
doc/easynmc-barrier-sync.txt missing

### ISSUE THREAD

**Issue by aol-nnov** [RC-MODULE/nmc-utils#4]
... but referenced in doc/getting-started.txt

**Comment by nekromant** [comment]
Barrier-sync was removed in favor of new aura-rpc, I will update docs ASAP.

**Comment by aol-nnov** [comment]
Aura wtf?!^W not a single mention anywhere around. I'm intrigued! :)
When will it be made available to the public?

**Comment by nekromant** [comment]
It is an opensource RPC library that now also has Neuromatrix DSP support (with zero-copy). We are using it for our matlab support package for MB77.07. Binaries come bundled with all the firmwares. However, Neuromatrix DSP transport as of now requires the 4.2.x experimental kernel branch with ION Memory Manager support to work properly. 

Sources and docs: 
http://github.com/nekromant/aura
http://github.com/nekromant/aura-httpd
http://github.com/nekromant/aura-cli

Neuromatrix example:
https://github.com/RC-MODULE/nmc-utils/tree/0.1.1/nmc-examples/aura-rpc

**Comment by aol-nnov** [comment]
Zero-copy is a tasty piece of pie, but unfortunately, 4.2.x is a no-go for us.

Any chance you could share easynmc-barrier-sync.txt though?
Also, could you advise how to achieve zero-copy data transfer between DSP and host CPU on 3.10.x kernel?

Thanks in advance!

**Comment by nekromant** [comment]
It was never implemented, since we went the RPC way. You may have a look at transport-nmc.c in aura repo, since it implements a very simple barrier sync for all the io under the hood.

If you need zero-copy the simplest way on 3.10.x would be either placing your buffer in neuromatrix memory (accessible via easynmc_handle->imem and easynmc_handle->imem32). If it doesn't fit - reserve a chunk of memory in dts, map it to userspace with a simple kernel driver and pass the pointer to Neromatrix (remember that nmc addresses memory in 32 bit words, so to the physical address of memory for the NMC would be (arm_address >> 2)

**Comment by aol-nnov** [comment]
Thank you for the comments, Andrey.

But it seems to me, that in our case it is impossible to use any of these two approaches (and zero-copy in general, sigh).

The reason is that the piece of code we're willing to offload to dsp processing is allocated in the middle of "multi tier" algorithm - memory allocation happens somewhere above and results should be passed "below".
So, in the middle of that chain we have two pointers to host RAM. One points to host data and another one points to destination buffer..

Oh, my zero-copy dreams..
Thanks very much, anyway!

**Comment by nekromant** [comment]
@aol-nnov The only way to deal with that - extend easymc driver to pin the pages of userspace ram and pass the scatter list to nmc. But this way you'll get your buffer as a set of (possibly not properly unaligned) pages on the DSP size.
